name: Release workflow

on:
  release:
    types: [published]

jobs:
  build-packages:
    name: Build Packages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'kiwiirc/kiwiirc_packager'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org/'

      - name: Setup Golang
        uses: actions/setup-go@v2

      - name: Build Packages
        run: |
          chmod +x build_packages.sh
          ./build_packages.sh

      - name: Upload Assets
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'packaged/*'
