name: Manual release workflow

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Build tag'
        required: true
        default: 'v'
      iteration:
        description: 'Build iteration'
        required: true
        default: '1'

jobs:
  build-packages:
    name: Build Packages

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'kiwiirc/kiwiirc_packager'
          ref: 'testing'

      - name: Install Dependencies
        run: |
          chmod +x ubuntu_debian_dependancies.sh
          ./ubuntu_debian_dependancies.sh

      - name: Build Packages
        run: |
          chmod +x build_packages.sh
          ./build_packages.sh -t ${{ github.event.inputs.tag }} -i ${{ github.event.inputs.iteration }}

      - name: Upload Assets
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'dist/*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.event.inputs.tag }}
